# Generated by Django 6.1.1 on 2026-09-15 02:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='datasets/%Y/%m/')),
                ('original_filename', models.CharField(max_length=255)),
                ('size_bytes', models.BigIntegerField()),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('ready', 'Ready'), ('failed', 'Failed')], default='uploaded', max_length=16)),
                ('n_cells', models.IntegerField(blank=True, null=True)),
                ('n_genes', models.IntegerField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('params', models.JSONField(default=dict)),
                ('preprocess_key', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('preprocessing', 'Preprocessing'), ('clustering', 'Clustering'), ('markers', 'Markers'), ('done', 'Done'), ('failed', 'Failed')], default='queued', max_length=16)),
                ('cache_hit', models.BooleanField(null=True)),
                ('n_clusters', models.IntegerField(blank=True, null=True)),
                ('timings', models.JSONField(default=dict)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='api.dataset')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarkerGene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_id', models.PositiveSmallIntegerField()),
                ('rank', models.PositiveSmallIntegerField()),
                ('gene', models.CharField(max_length=64)),
                ('score', models.FloatField()),
                ('log2fc', models.FloatField()),
                ('pct_in', models.FloatField()),
                ('pct_out', models.FloatField()),
                ('pval', models.FloatField()),
                ('padj', models.FloatField()),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markers', to='api.run')),
            ],
            options={
                'ordering': ['cluster_id', 'rank'],
                'indexes': [models.Index(fields=['run', 'cluster_id'], name='api_markerg_run_id_0300a3_idx')],
            },
        ),
        migrations.CreateModel(
            name='CellCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell_barcode', models.CharField(max_length=64)),
                ('cluster_id', models.PositiveSmallIntegerField()),
                ('umap_x', models.FloatField()),
                ('umap_y', models.FloatField()),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='api.run')),
            ],
            options={
                'indexes': [models.Index(fields=['run', 'cluster_id'], name='api_cellclu_run_id_761092_idx')],
                'constraints': [models.UniqueConstraint(fields=('run', 'cell_barcode'), name='uniq_run_barcode')],
            },
        ),
    ]
