# Generated by Django 6.1.1 on 2026-09-16 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='job_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
